### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by punjie** [zakalibit/RTEPlayer.bundle#3]
Thanks for the channel! The links seem to work except there is no sound. I'm a novice at this. Can you help me?

**Comment by zakalibit** [comment]
Are you using the web interface, or some other client?

**Comment by punjie** [comment]
Sorry, I have no idea. I only know that I downloaded the channel and successfully added it to Plex , but get no sound. I'm not tech fluent or savvy.

**Comment by zakalibit** [comment]
Is it in a browser? What OS (widnows/linux)? I it is a browser, witch one (chrome, mozilla, ie explorer)?
Does youtube, or other web sites with video work and have sound in the same browser?
In settings->Player try to change these options:

Allow Direct Play of AC3 Audio
Prefer AAC Audio

**Comment by zakalibit** [comment]
As well in settings try disable Direct Play

**Comment by punjie** [comment]
Thanks. I'll get help trying your suggestions and let you know.

**Comment by punjie** [comment]
I'm working on a MacBook Pro (OS X Yosemite)  and in Firefox. YouTube and other video sounds work in same browser. Tried all suggestions, but to no avail.

**Comment by punjie** [comment]
It's working on my smart tv, but not the other tv of the same brand. Thanks a lot for all you hard work on this one!
